### ISSUE TITLE
Error when trying to monitor a process

### ISSUE THREAD

**Issue by yannispapadakis** [01org/intel-cmt-cat#18]
I am trying to monitor a process with the following command:
`./pqos -p llc:69866`
but I keep receiving the same error message:
`PID 69866 monitoring start error,status 1`
Am I doing something wrong?

**Comment by tkanteck** [comment]
Do you run it as root?
Could you copy paste output of "./pqos -s -v" please?

**Comment by yannispapadakis** [comment]
I do not have root privilege, and the PID is valid, but I found what's wrong. `./pqos -s -v` mentions that PID monitoring is not supported, because it requires Kernel version 4.1 or higher.
Anyway, thank you for your help!

**Comment by tkanteck** [comment]
If possible and makes sense, pin your application to core(s) using taskset, Core granularity 
resource monitoring may be sufficient in such case. The other alternative is to upgrade the kernel.

**Comment by yannispapadakis** [comment]
Yes, I already use taskset to pin my applications to one core. I updated the kernel, and it's working now!
I noticed that when I monitor a PID, the "Core" column says "N/A" (not available I suppose).
Is there anything I can do to fix that?

**Comment by tkanteck** [comment]
OK I see, in your case cores are shared by multiple different applications.
When you apply taskset and there is nothing else running on the cores then you can simply monitor cores rather than a task. See [this example](https://github.com/01org/intel-cmt-cat/wiki/Usage-Examples#example-cmtmbm-usage-scenario) on project wiki.
Yeah, N/A is displayed in "Core" column at the moment. The idea was to put task core mask there but it is to be done.
